import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "35AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <div className=" text-center p-4">
          <a href="https://beian.miit.gov.cn/" target="_blank">京ICP备2022010315号-3</a>
        </div>
      </body>
    </html>
  );
}
