# workflow名称
name: deploy-to-aliyun

# 对应第1步，main代码变动执行该workflow
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    # 定义job运行环境，使用linux环境
    runs-on: ubuntu-latest
    steps:
    # 对应第2步，借助已有脚本拉取代码
    - name: Checkout
      uses: actions/checkout@v4
      
    # 第3步的准备工作，先配置好node环境
    - uses: actions/setup-node@v4
      with:
        node-version: '20'

    # 对应第3步，执行打包命令
    - name: 'Build'
      run: |
        npm i
        npm run build
        
    # 对应第4、5步，配置参数登陆服务器+拷贝到指定目录
    - name: Upload
      uses: appleboy/scp-action@master
      with: 
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        # 拷贝 .next、public文件夹和package.json文件到服务器指定目录
        source: ".next/,public/,package.json"
        target: "/home/35ai"
    
    # 对应第6步，重启安装依赖、后端服务2
    - name: Server Reload
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          whoami
          cd /home/35ai
          /root/.nvm/versions/node/v22.4.0/bin/npm i
          /root/.nvm/versions/node/v22.4.0/bin/pm2 reload 35ai
